version: "3"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    volumes:
      - ./www:/app

  db:
    image: mysql
    command: ['--default-authentication-plugin=mysql_native_password','--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    restart: always
    environment:
      MYSQL_DATABASE: devbuild
      MYSQL_ROOT_PASSWORD: root
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"   
  